version: "3.7"
services:
    # image project
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        container_name: php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-eti

    # nginx
    nginx:
        image: nginx:alpine
        container_name: web
        restart: unless-stopped
        ports:
            - 8180:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-eti

networks:
    laravel-eti:
        driver: bridge
